import { type NextRequest } from 'next/server';

// Simulated delay between streamed tokens (ms)
const TOKEN_DELAY_MS = 18;

function generateLessonPlan(topic: string): string {
  return `# Lesson Plan: ${topic}

## Overview
This lesson introduces students to **${topic}** through a blend of direct instruction, guided exploration, and hands-on practice.

**Grade Level:** Adaptable (grades 3–8)
**Duration:** 50 minutes

---

## Learning Objectives

By the end of this lesson, students will be able to:
1. Define and explain the core concepts related to ${topic}
2. Identify real-world examples and applications
3. Analyze the importance of ${topic} in context
4. Apply their understanding through a brief activity

---

## Materials
- Whiteboard or projector
- Student notebooks or graphic organizer handouts
- Reference texts or short articles (provided separately)
- Exit ticket slips

---

## Lesson Outline

### Warm-Up (5–7 minutes)
Open with a brief **think-pair-share**: *"What do you already know about ${topic}? What questions do you have?"* Record student responses on the board to activate prior knowledge and set a purpose for learning.

### Direct Instruction (12–15 minutes)
Introduce core vocabulary and concepts using visuals and examples. Focus on depth over breadth — three ideas taught well beats six ideas taught shallowly.

Key concepts to cover:
- Definition and context
- How it connects to students' prior knowledge
- A memorable analogy or real-world comparison

### Guided Practice (10–12 minutes)
Work through 2–3 examples as a class. Use cold-call and turn-and-talk questioning to check understanding. Address common misconceptions directly.

### Independent Practice (8–10 minutes)
Students complete a short activity independently — a graphic organizer, brief writing prompt, or worksheet. Circulate and provide targeted support.

### Closure & Exit Ticket (5 minutes)
Ask 2–3 students to share a key takeaway. Distribute exit tickets:
> *"In one sentence, explain ${topic} to someone who has never heard of it."*

---

## Differentiation

**For students who need more support:**
- Provide a vocabulary reference sheet
- Pair with a partner during guided practice
- Offer a sentence frame for the exit ticket

**For advanced learners:**
- Extend with a challenge question
- Ask them to connect the topic to another subject area
- Invite them to create their own example

---

## Assessment
- **Formative:** Teacher observation during guided practice; exit ticket responses
- **Summative:** Include ${topic} in the next unit quiz or project rubric

---

*Generated by Nisa Lesson Plan Generator*`;
}

export async function POST(request: NextRequest) {
  const body = await request.json();
  const messages: Array<{ role: string; content: string }> = body.messages ?? [];
  const lastMessage = messages[messages.length - 1];
  const userContent = lastMessage?.content ?? '';

  if (userContent.trim().toUpperCase() === 'ERROR') {
    return new Response('Internal Server Error', { status: 500 });
  }

  const topic = userContent.trim() || 'your topic';
  const lessonPlan = generateLessonPlan(topic);

  const encoder = new TextEncoder();
  const stream = new ReadableStream({
    async start(controller) {
      try {
        for (const char of lessonPlan) {
          // AI SDK UI data stream protocol: text delta parts are prefixed with "0:"
          controller.enqueue(encoder.encode(`0:${JSON.stringify(char)}\n`));
          await new Promise<void>(resolve => setTimeout(resolve, TOKEN_DELAY_MS));
        }

        const usage = { promptTokens: 20, completionTokens: lessonPlan.length };
        controller.enqueue(
          encoder.encode(
            `e:${JSON.stringify({ finishReason: 'stop', usage, isContinued: false })}\n`,
          ),
        );
        controller.enqueue(
          encoder.encode(`d:${JSON.stringify({ finishReason: 'stop', usage })}\n`),
        );
        controller.close();
      } catch {
        controller.error(new Error('Stream interrupted'));
      }
    },
  });

  return new Response(stream, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'x-vercel-ai-data-stream': 'v1',
    },
  });
}
